-- 
-- Initial data for the `districtdb_jobs` table.
-- Bruce Schurmann
-- See https://github.com/brucesch/districtdb/wiki
--


LOCK TABLES `districtdb_jobs` WRITE;

INSERT INTO `districtdb_jobs` VALUES (1,'UC','Unit Commissioner','Pack',1),
  (2,'ADC','Assistant District Commissioner','Pack',1),
  (3,'CM','Cubmaster','Pack',1),
  (4,'SM','Scoutmaster','Troop',1),
  (5,'NL','Crew Advisor','Crew',1),
  (6,'CC','Unit Committee Chair','Pack',1),
  (7,'TL','Tiger Den Leader','Pack',0),
  (8,'DL','Den Leader','Pack',0),
  (9,'WL','Webelos Den Leader','Pack',0),
  (10,'SA','Assistant Scoutmaster','Troop',0),
  (11,'CA','Assistant Cubmaster','Pack',0),
  (12,'UOTH','Unit Other','Pack',0),
  (13,'EA','Explorer Post Advisor','Post',1),
  (14,'MT','Mate','Ship',0),
  (15,'SK','Skipper','Ship',1),
  (16,'CR','Charter Org Representative','Pack',1),
  (17,'MC','Unit Committee Member','Pack',0),
  (18,'DE','District Executive','District',0),
  (19,'DD','District Director','District',0),
  (20,'DP','District Professional','District',0),
  (21,'81','District Commissioner','District',1),
  (22,'61','District Chair','District',1),
  (23,'62','District Vice Chair','District',1),
  (24,'DSC','District Subcommittee Chair','District',0),
  (25,'75','District Committee Member','District',0),
  (26,'COE','Charter Org Executive','CharterOrg',1),
  (27,'CO','Council','Council',0),
  (28,'PA','Parent','Pack',0),
  (29,'42','Merit Badge Counselor','District',0),
  (30,'NA','Crew Associate Advisor','Crew',0),
  (31,'WA','Assistant Webelos Den Leader','Pack',0),
  (32,'DA','Assistant Den Leader','Pack',0),
  (33,'RT','District Roundtable Commissioner','District',1),
  (34,'DOTH','District Other','District',0),
  (35,'CSRT','Cub Scout Roundtable Commissioner','District',1),
  (36,'BSRT','Boy Scout Roundtable Commissioner','District',1),
  (37,'VRT','Venture Scout Roundtable Commissioner','District',1),
  (38,'VTC','Team Coach','Varsity',1),
  (39,'VPA','Program Adviser','Varsity',0),
  (40,'ACM','Activities Committee Member','District',0),
  (41,'ADCM','Advancement Committee Member','District',0),
  (42,'CCM','Camping Committee Member','District',0),
  (43,'COCM','Communication Committee Member','District',0),
  (44,'FCM','Finance Committee Member','District',0),
  (45,'MCM','Membership Committee Member','District',0),
  (46,'TCM','Training Committee Member','District',0),
  (47,'UADV','Unit Advancement Chair','Pack',0),
  (48,'TEAG','Troop Eagle Coordinator','Troop',0),
  (49,'TCC','Troop Camping Coordinator','Troop',1),
  (50,'PCC','Pack Camping Coordinator','Pack',1),
  (51,'CCC','Crew Camping Coordinator','Crew',1),
  (52,'AOC','Adult OA Coordinator','Troop',1),
  (53,'HSC','Health and Safety Coordinator','Pack',1),
  (54,'NCM','Nominating Committee Member','District',0),
  (55,'CPRC','Camporee Chair','District',1),
  (56,'CSDC','Cub Scout Day Camp Director','District',0),
  (57,'DADV','District Advisor','District',0),
  (58,'DVC','District Vice Commissioner','District',1),
  (59,'OACA','OA Chapter Advisor','District',1),
  (60,'PK','Popcorn Kernel','District',1),
  (61,'WWC','Webelos Woods Chair','District',1),
  (62,'ACC','Activities Committee Chair','District',1),
  (63,'ADVC','Advancement Committee Chair','District',1),
  (64,'CCMC','Camping Committee Chair','District',1),
  (65,'COCC','Communication Committee Chair','District',1),
  (66,'FCC','Finance Committee Chair','District',1),
  (67,'MCC','Membership Committee Chair','District',1),
  (68,'NC','Nominating Committee Chair','District',1),
  (69,'TRCC','Training Committee Chair','District',1),
  (70,'UPK','Unit Popcorn Kernel','Pack',1),
  (71,'WLI','Webelos Liaison','Troop',0),
  (72,'PRI','Principal','CharterOrg',1),
  (73,'APRI','Assistant Principal','CharterOrg',0),
  (74,'TEA','Teacher','CharterOrg',0),
  (75,'EMP','Employee','Company',0),
  (81,'UC','Unit Commissioner','Troop',1),
  (82,'ADC','Assistant District Commissioner','Troop',1),
  (83,'CC','Unit Committee Chair','Troop',1),
  (84,'UOTH','Unit Other','Troop',0),
  (85,'CR','Charter Org Representative','Troop',1),
  (86,'MC','Unit Committee Member','Troop',0),
  (87,'PA','Parent','Troop',0),
  (88,'UADV','Unit Advancement Chair','Troop',0),
  (89,'HSC','Health and Safety Coordinator','Troop',1),
  (90,'UPK','Unit Popcorn Kernel','Troop',1),
  (91,'UC','Unit Commissioner','Crew',1),
  (92,'ADC','Assistant District Commissioner','Crew',1),
  (93,'CC','Unit Committee Chair','Crew',1),
  (94,'UOTH','Unit Other','Crew',0),
  (95,'CR','Charter Org Representative','Crew',1),
  (96,'MC','Unit Committee Member','Crew',0),
  (97,'PA','Parent','Crew',0),
  (98,'UADV','Unit Advancement Chair','Crew',0),
  (99,'HSC','Health and Safety Coordinator','Crew',1),
  (100,'UPK','Unit Popcorn Kernel','Crew',1),
  (101,'UC','Unit Commissioner','Ship',1),
  (102,'ADC','Assistant District Commissioner','Ship',1),
  (103,'CC','Unit Committee Chair','Ship',1),
  (104,'UOTH','Unit Other','Ship',0),
  (105,'CR','Charter Org Representative','Ship',1),
  (106,'MC','Unit Committee Member','Ship',0),
  (107,'PA','Parent','Ship',0),
  (108,'UADV','Unit Advancement Chair','Ship',0),
  (109,'HSC','Health and Safety Coordinator','Ship',1),
  (110,'UPK','Unit Popcorn Kernel','Ship',1),
  (111,'UC','Unit Commissioner','Post',1),
  (112,'ADC','Assistant District Commissioner','Post',1),
  (113,'CC','Unit Committee Chair','Post',1),
  (114,'UOTH','Unit Other','Post',0),
  (115,'CR','Charter Org Representative','Post',1),
  (116,'MC','Unit Committee Member','Post',0),
  (117,'PA','Parent','Post',0),
  (118,'UADV','Unit Advancement Chair','Post',0),
  (119,'HSC','Health and Safety Coordinator','Post',1),
  (120,'UPK','Unit Popcorn Kernel','Post',1),
  (121,'UC','Unit Commissioner','Varsity',1),
  (122,'ADC','Assistant District Commissioner','Varsity',1),
  (123,'CC','Unit Committee Chair','Varsity',1),
  (124,'UOTH','Unit Other','Varsity',0),
  (125,'CR','Charter Org Representative','Varsity',1),
  (126,'MC','Unit Committee Member','Varsity',0),
  (127,'PA','Parent','Varsity',0),
  (128,'UADV','Unit Advancement Chair','Varsity',0),
  (129,'HSC','Health and Safety Coordinator','Varsity',1),
  (130,'UPK','Unit Popcorn Kernel','Varsity',1),
  (131,'FR','Friend','District',0);

UNLOCK TABLES;

